# Get all transactions
http://localhost:5000/api/v1/transactions

###
# Add transactions
POST http://localhost:5000/api/v1/transactions
content-type: application/json

{
    "text": "random 2",
    "amount": 600
}
###
# delete transactions
DELETE http://localhost:5000/api/v1/transactions/